name: cafmet
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  barcode_widget: ^2.0.4
  csv: ^6.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.0
  flutter_provider: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.5
  google_maps_flutter: ^2.2.8
  gsheets: ^0.5.0
  http: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.5.0
  
  mobile_scanner: ^4.0.1
  open_file: ^3.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins  
      fonts:
        - asset: assets/Poppins_Regular.ttf  
    - family: Montserrat  
      fonts:
        - asset: assets/Montserrat.ttf 
        